### ISSUE TITLE
Problem: Not yet published to NPM 

### ISSUE THREAD

**Issue by mbalex99** [getditto/react-ditto#1]
This library needs to be published to npm.

**Comment by hamchapman** [comment]
How do we want releases of this to work? I think in the past you said that you'd like them to be separate from the general SDK releases.

Would it be enough to have a script in this repo (or perhaps in the monorepo) that pushed up a new release of this library?

**Comment by mbalex99** [comment]
Let's hold off until the auth work lands in JavaScript SDK so we can make the appropriate hooks.
