### ISSUE TITLE
Implement LiveQuery and Sync Data of Big Peer to Small Peer for ReactNative

### ISSUE THREAD

**Issue by crosskpixel** [getditto/react-ditto#62]
migration from atlas, i need sync collecton from BigPeer to my local ditto.

"react-native": "0.71.11"
"@dittolive/ditto": "^4.8.1"

**Comment by jenpalma-ditto** [comment]
Hi @crosskpixel ! Thank you for raising this, I will be following up with you with more information via the support ticket that you have created.

**Comment by crosskpixel** [comment]
This repository explain how ditto will work with react native https://github.com/getditto/react-native-sample-app
