### ISSUE TITLE
When upload to apple connect the DittoFramework on iOS don't assign CFStringVersion

### ISSUE THREAD

**Issue by crosskpixel** [getditto/react-ditto#66]
![Screenshot at Oct 01 22-01-26](https://github.com/user-attachments/assets/90b192c7-7568-4469-8766-0dd41bbda717)
![Screenshot at Oct 01 22-00-47](https://github.com/user-attachments/assets/4773c46f-5cc8-4641-b574-90799606a470)
![Screenshot at Oct 01 22-00-37](https://github.com/user-attachments/assets/8d5e626a-d6eb-411c-82c4-0759a2abf6d9)
i added manually for test.

i have been using react native 0.71, the app works com android and ios. the problem just occurs to send to apple connect, i believe be more easier solve this than upgrade entire app.

**Comment by crosskpixel** [comment]
i updated my project to the last version of react native, and don't works too. in android is 100%

**Comment by jenpalma-ditto** [comment]
Hi @crosskpixel Thanks for raising this concern! We will be touching base with you on this via the Support ticket created.

**Comment by crosskpixel** [comment]
Solved! follow the next steps

open with any textEditor
_/ios/Pods/DittoReactNativeIOS/DittoReactNative.xcframework/Info.plist_


```
//and add the lines below
<key>CFBundleShortVersionString</key>
<string>4.8.2</string>
```

After that open your XCode and open using  File -> Open
/ios/Pods/DittoReactNativeIOS/DittoReactNative.xcframework/ios-arm64/DittoReactNative.framework/Info.plist
/ios/Pods/DittoReactNativeIOS/DittoReactNative.xcframework/ios-arm64_x86_64-simulator/DittoReactNative.framework/Info.plist

manually put into this two files the
CFBundleShortVersionString - String - 4.8.2 or newer.
![image](https://github.com/user-attachments/assets/8ad31052-f2cf-4175-8798-83ee843a4862)

Finally build & archive your .ipa and will be accepted in Apple Connect.
